[package]
name = "vba_interpreter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vba-interpreter-lib = { path = "vba-interpreter-lib" }
